### ISSUE TITLE
Report Viewer Bug Fixes and Enhancements

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#1000]
This issue replaces #710 for newer tasks related to bug fixes and enhancements of the report viewer after the [4.2.0](https://github.com/jplag/JPlag/releases/tag/v4.2.0) release. The goal is to gather all report viewer-related TODOs until it reaches a stable enough state to switch to single issues.

## Modernization

The report viewer moves from [webpack](https://[webpack](https://webpack.js.org/).js.org/) to [vite](https://vitejs.dev/). This includes:

- [x] Setup the new project and fix inconsistencies
- [x] Move from vuex to [pinia](https://pinia.vuejs.org/cookbook/migration-vuex.html) for state management
- [ ] Fix remaining problems with legacy node dependencies like `Path` and `require`
- [ ] Add husky for the pre-commit running of lint and prettier
- [ ] Add unit and e2e test boilerplates
- [ ] Have a look at the `package.json` whether there are dependencies not needed anymore
- [ ] Test and replace report viewer

## Major enhancements

These enhancements are cross-cutting and subsume some of the other bug fixes and enhancements. They are meant as placeholders for bigger tasks toward a stable report viewer.

- [ ] Switch from webpack to vite, see above
- [ ] Use a frontend framework, e.g., [bootstrap 5+](https://getbootstrap.com/). The current version of the report viewer is styled manually which often breaks (and does not look that good).
- [ ] Enhance internal code quality. The general code quality was enhanced recently, but there are still major code smells and problems, e.g., in components like `CodePanel.vue`
- [ ] Write more test cases. vite offers comprehensive and easy-to-use testing capabilities with [vitest](https://vitest.dev/) and [playwright](https://playwright.dev/).
- [ ] Move from a deployed report viewer by us back to a local version that is started by the main JPlag program 

## Cluster enhancements

These enhancements relate to the clustering feature which currently only has limited support from the report viewer.

* [ ] the cluster button for comparison in the overview should only be shown if there are more than two submissions in the cluster, as the visualization offers no insights for pairs (added by @tsaglam)
* [ ] the somewhat non-descriptive clustering button should be replaced with a better one. It should show the number of submissions per cluster and maybe the avg similarity of the cluster, e.g. like [this](https://user-images.githubusercontent.com/4396919/212716165-3602a57b-4333-40f5-8c34-bd40f07a451d.png) (added by @tsaglam)
* [ ] Cluster should be visualized with a graph with submissions as nodes and comparisons as edges where the edges are thicker when the avg similarity is higher, e.g. like [this](https://user-images.githubusercontent.com/4396919/212717885-26ede9b9-1bb9-4e87-80fe-3c42f6e9b94f.png) (added by @tsaglam)
* [ ] The old cluster visualization should be accessible as well, but as a non-default version name "submissions-relative" (added by @tsaglam)
* [ ] Color the table of matches based on the identified clusters (should be optional, e.g., by using a checkbox)

## Other enhancements
* [ ] The landing page should show the current version number, maybe even the minimal required version number (proposed in #963)
* [ ] The overview should show the number of parsed submissions
* [ ] The comparison view should either show the max similarity or just bother similarities for the submissions themselves. The average similarity should be denoted as such (added by @tsaglam)
* [ ] Add button "collapse all" to the comparison view
* [ ] The histogram should have the possibility to switch to a log scale (added by @tsaglam)
* [ ] Support opening comparison views in new tabs
* [ ] Highlight base code, e.g., gray
* [ ] Hiding the names should replace them with some first names from the chair with a random number. This could also include replacing the names in the shown source code
* [ ] Supporting a dark mode (e.g., by user choice or even by default)
* [ ] Change comparison view file order, e.g., based on packages rather than alphabetical 
* [ ] Add a printable view or a possibility to generate printable reports (see #754 for details)
* [ ] Complete UI Overhaul - enhance overall frontend design/impression
* [ ] The CD [deployed version](https://jplag.github.io/JPlag/) should have sample files ready to go (added in the deployment pipeline)
* [ ] A new, easy-to-use code similarity view that hides any details (ask @sebinside for more details)

## Open bugs
* [ ] The back button in the comparison view is in an awkward position
* [ ] Syntax highlighting in the comparison view seems to be broken for JDoc comments (added by @tsaglam)
* [ ] If there is only one root folder, the root folder name should not be visible in the report viewer
* [ ] Support for same root directory names
* [ ] The distribution seems to be broken for some submission sets, which might be connected to switching between metrics (added by @tsaglam)
* [ ] Switching between `avg` and `max` metric freezes the UI if there are many submissions in the overview
* [ ] The max metric selection is not stored; after returning from a comparison view, it is reset to avg (added by @tsaglam)
* [ ] Fix the indent of code with different line numbers 
* [ ] Shuffle colors in the array or find a different generation algorithm
* [ ] Normalize file paths in the Report Viewer, e.g., to mitigate problems such as discussed in #923

## Build/CI/Dev tasks
* [ ] Add automatic testing to the Report Viewer actions pipeline
* [ ] Remove building core JPlag from the Report Viewer actions pipeline (Do not run maven if only the report viewer is changed)
* [ ] Include and enforce eslint or similar, e.g., using spotless
* [ ] Older versions of the report viewer shall be deployed somewhere for end users of the older versions (starting with version `4.0.0`)

**Comment by sebinside** [comment]
@jplag/hiwi I added all the new feature requests and comments from our workshop

**Comment by Alberth289346** [comment]
@tsaglam For Cluster Enhancements, did you consider using DSMs rather than graphs to display them? https://dsmweb.org/clustering-a-dsm/  for a simple example. No personal experience, but afaik they tend to be more compact.

**Comment by tsaglam** [comment]
> For Cluster Enhancements, did you consider using DSMs rather than graphs to display them?

We have not considered DSMs yet, but it is an interesting idea. In the long run, we want to offer different visualizations for clusters, so this could be one of them.

**Comment by tsaglam** [comment]
Also regarding the same discussion, maybe we can take a look at this work by Novak et al.: https://ieeexplore.ieee.org/abstract/document/9488644

**Comment by Kr0nox** [comment]
Things that should be disgussed:
- [ ] Are console logs wanted in a normal error free run?
- [ ] Should the light-/dark-mode button be moved? If so where?

**Comment by Kr0nox** [comment]
With the release of version 5.0.0 the report viewer reached a stable state and the majority of issues from this are solved. Due to this we decided to move away from this collection to individual issues.
All problems that are still open are now individual issue: #1601 #1602  #1603 #1604 #1605

**Comment by sebinside** [comment]
RIP #1000 and great progress!

**Comment by tsaglam** [comment]
RIP #1000 🥲
