### ISSUE TITLE
Text frontend unnecessarily overcomplicated

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#556]
The [text frontend](https://github.com/jplag/JPlag/tree/master/jplag.frontend.text) is unnecessarily overcomplicated, as the outdated ANTLR grammar can be replaced with functionality provided by CoreNLP. This reduces the size and the complexity.

The grammar essentially splits a text file into words, punctuations, spaces, newlines, and special characters:
https://github.com/jplag/JPlag/blob/24daec9232849befe98499b53c5aa414a21a8c01/jplag.frontend.text/src/main/antlr/text.g#L75-L104

However, only the words are transferred into tokens:
    
> "Don't give me 2 of those! :("

will lead to the following tokens: ```[Don, t, give, me, 2, of, those]```

<br>

**Tasks to do:** 

- [ ] Remove the grammar and change the `ParserAdapter` as follows to replace the [ANTLR grammar](https://github.com/jplag/JPlag/blob/master/jplag.frontend.text/src/main/antlr/text.g)
    - It reads in a file directly
    - Splits the containing text into segments with a call to the CoreNLP tokenizer (see [this example](https://github.com/Gram21/TokenizerExample))
    - Creates the JPlag tokens directly without the grammar from the words created with CoreNLP
    -  The class InputState will become obsolete
- [ ] Make sure to be mindful of all [edge cases](https://github.com/jplag/JPlag/blob/f3b0d1f371cf5b2d03bff7432a4212180165c5d5/jplag.frontend.text/src/main/antlr/text.g#L73-L102).
- [ ] Verify that the old and the new text frontend behave similarly

**Comment by dfuchss** [comment]
We could also think about enhancing this frontend by using standard language techniques (stemming etc.) to find even more similarities.

**Comment by tsaglam** [comment]
> We could also think about enhancing this frontend by using standard language techniques (stemming etc.) to find even more similarities.

I had the same idea and was considering this as a future PISE topic. Maybe we can use CoreNLP here.
