### ISSUE TITLE
Report Viewer Bugfixes and Enhancements

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#710]
The new report viewer has been introduced with the release [4.0.0](https://github.com/jplag/JPlag/releases/tag/v4.0.0). Although this represents a giant step forward compared to the old string-concatenating HTML-file-generation, there is still some work to do for the next releases of JPlag. This issue shall gather all these TODOs. It replaces #357, #658, and #686.

## Bugs
* [x] Files and matches shall be represented based on their full path (incl. root directory). This shall prevent collisions in the report viewer match display. Please also see the discussions in #686 and #658. The quick fix from #691 has to be therefore reverted. In the viewer, the file paths shall be shown in an abbreviated way if they are too long. File paths shall be platform-independent. (Addressed in #785)
* [x] The report generation does overwrite source code files if they have the same name because all files are "flat mapped", i.e., written in one single folder per submission. It does not throw an error but will put out wrong results that might be noticed later (or even not noticed at all). Here, the solution is probably to preserve the original folder structure also in the resulting zip file in the submissions folder. This could also be based on selecting which files to copy. This problem probably also affects the multi-root and subdir features. (Addressed in #785)
* [x] The ends of displayed matches are sometimes off by one. This is probably a display bug as the information is correctly represented in the generated JSON files. (Addressed in #816)
* [x] Clustering shall be reenabled (disabled in #691) and tested comprehensively (Addressed in #816)
* [x] Match highlighting in the comparison view seems to be broken for single-file submissions (added by @tsaglam)
* [x] Same submission names break the ComparisonView, please see below (Addressed in #829)
* [x] The folder in the results holding the submission files should be renamed from "submissions" to "files" (Addressed in #829)
* [x] Clicking on the colored match highlighting sometimes does not work (or stops working after several clicks), e.g., with [this example](https://github.com/jplag/JPlag/files/10093727/SameSubmissionName.zip), (Addressed in #855)

## Enhancements
* [x] The [main screen](https://jplag.github.io/JPlag/) where the files are dropped should contain a line of text that states that no files get uploaded anywhere (Addressed in #829)
* [x] The code comparison view always shows "submission 1" and "submission 2", but should show the names. But not if the names are hidden (Addressed in #829)
* [x] In the code comparison view, the left sidebar should be visible by default (Addressed in #829)
* [x] In the comparison view, there should be a "back" button (added by @tsaglam), (Addressed in #855)
* [x] In the code comparison view, code cannot be selected (added by @tsaglam), (Addressed in #877)
* [x] Enhance the version check introduced by #691 and display more than a console warning, e.g., a prompt displaying the warning. There should be a warning for development versions (0.0.0) and version mismatches. Load the report viewer version from a JSON file in src directory with the content `{"jplag_version":{"major":0,"minor":0,"patch":0}}`
* [x] Enable collapsing by clicking on the file header in the comparison view (Addressed in #879)
* [x] Show a warning if some/all comparison files are missing, in the console log and also in the report viewer when scrolling down, e.g., because there are 1000 comparisons, but only 100 are included in the resulting zip file
* [x] Change the color scheme of matches (something without implicit semantics)
* [x] Enhance test coverage (> 0%), focus on unit tests. [Jest](https://jestjs.io/) is a popular framework for this, [here](https://vuejs.org/guide/scaling-up/testing.html) can be found additional information about testing with Vue
* [x] Investigate the real bad performance of navigating to the overview, add incremental rendering to overcome these issues
* [x] Make the report viewer more resilient to errors and properly report them. Currently, even minor parsing errors break the complete viewer without any message to the end user (besides console printing of the deceased viewer).
* [x] Enhance logging in both the JSON serializer and the report viewer code.
* [x] Redirect to file upload if the overview or a comparison view is reloaded (i.e., on error after reload)

## Cluster enhancements
* [ ] the cluster button for a comparison in the overview should only be shown if there are more than two submissions in the cluster, as the visualization offers no insights for pairs (added by @tsaglam)
* [ ] the somewhat non-descriptive clustering button should be replaced with a better one. It should show the number of submissions per clusters and maybe the avg similarity of the cluster, e.g. like [this](https://user-images.githubusercontent.com/4396919/212716165-3602a57b-4333-40f5-8c34-bd40f07a451d.png) (added by @tsaglam)
* [ ] Cluster should be visualized with a graph with submissions as nodes and comparisons as edges where the edges are thicker when the avg similarity is higher, e.g. like [this](https://user-images.githubusercontent.com/4396919/212717885-26ede9b9-1bb9-4e87-80fe-3c42f6e9b94f.png) (added by @tsaglam)
* [ ] The old cluster visualization should be accessible as well, but as a non-default version names "submissions-relative" (added by @tsaglam)
* [ ] Color the table of matches based on the identified clusters (should be optional, e.g., by using a checkbox)

## Other enhancements
* [ ] The landing page should show the current version number, maybe even the minimal required version number (proposed in #963)
* [ ] The overview should show the number of parsed submissions
* [ ] The comparison view should either show the max similarity, or just bother similarities for the submissions themselves. The average similarity should be denoted as such (added by @tsaglam)
* [ ] Add button "collapse all" to the comparison view
* [ ] The histogram should have the possibility to switch to a log scale (added by @tsaglam)
* [ ] Support opening comparison views in new tabs
* [ ] Highlight base code, e.g., gray
* [ ] Hiding the names should replace them with some first names from the chair with a random number. This could also include replacing the names in the shown source code
* [ ] Supporting a dark mode (e.g., by user choice or even by default)
* [ ] Change comparison view file order, e.g., based on packages rather than alphabetical 
* [ ] Add a printable view or a possibility to generate printable reports (see #754 for details)
* [ ] Complete UI Overhaul - enhance overall frontend design/impression
* [ ] The CD [deployed version](https://jplag.github.io/JPlag/) should have sample files ready to go (added in the deployment pipeline)
* [ ] A new, easy-to-use code similarity view that hides any details (ask @sebinside for more details)

## Open bugs
* [ ] The back button in the comparison view is in an awkward position
* [ ] Syntax highlighting in the comparison view seems to be broken for JDoc comments (added by @tsaglam)
* [ ] If there is only one root folder, the root folder name should not be visible in the report viewer
* [ ] Support for same root directory names
* [ ] The distribution seems to be broken for some submission sets, which might be connected to switching between metrics (added by @tsaglam)
* [ ] The comparison view occasionally freezes after clicking on too many matches (needs additional investigation)
* [ ] Switching between `avg` and `max` metric freezes the UI if there are many submissions in the overview
* [ ] The max metric selection is not stored; after returning from a comparison view, it is reset to avg (added by @tsaglam)
* [ ] Fix the indent of code with different line numbers 
* [ ] Shuffle colors in the array or find a different generation algorithm
* [ ] Normalize file paths in the Report Viewer, e.g., to mitigate problems such as discussed in #923

## Build/CI/Dev tasks
* [ ] Move Report Viewer from webpack to vite
* [ ] Add automatic testing to the Report Viewer actions pipeline
* [ ] Remove building core JPlag from the Report Viewer actions pipeline
* [ ] Include and enforce eslint
* [ ] Older versions of the report viewer shall be deployed somewhere for end users of the older versions (starting with version `4.0.0`)
* [ ] Include automated testing in the report viewer action
* [ ] Do not run maven if only the report viewer is changed

**Comment by tsaglam** [comment]
I just added a few enhancements and bugs from this year's prog grading. For more details ask me.

**Comment by sebinside** [comment]
@cyfml While same file names now work (thank you!), same submission names and same root directory names break the comparison view. I attached two example down below. Both use the multi root feature, i.e., `-old root1 -new root2`. After we merged PR #785, please have a look at it in a new PR.

[SameSubmissionName.zip](https://github.com/jplag/JPlag/files/10093727/SameSubmissionName.zip)
[SameRootName.zip](https://github.com/jplag/JPlag/files/10093729/SameRootName.zip)

**Comment by cyfml** [comment]
@sebinside Ok.

**Comment by tsaglam** [comment]
@cyfml @sebinside the syntax highlighting for single-file submissions is currently broken. The reason is that we put the file in a folder with the same name in the "submissions" folder of the zip. E.g. imagine a submission is just one file `Sub.java` without a folder. Then your file structure in the zip looks like this: `submissions/Sub.java/Sub.java`. However, in the match files, the id will be `"id1": "Sub.java",` and the file will be `"file1": "",`, thus the viewer cannot find the file and no highlighting is shown. @cyfml can you fix this?

There are two ways to fix this:
- Store single-file submissions directly in the `submissions` folder of the zip, and adapt the viewer accordingly
- Ensure that for single-file submissions, the match files have the file name as `id` value and as `file` value

**Comment by cyfml** [comment]
@tsaglam After today's classes, i will try to fix it.

**Comment by tsaglam** [comment]
> @tsaglam After today's classes, i will try to fix it.

I think you already did with your last PR, so should be fine

**Comment by cyfml** [comment]
@sebinside @tsaglam I found a issue about the highlighting. In the LineOfCode Component, one single line of codes will be highlighted. The codes are not highlighted as a whole. That is why highlighting is broken for JDoc. It also influences the performance of the report-viewer, because each line of codes will call highlight JS.

**Comment by cyfml** [comment]
@sebinside
The requirement: Load the report viewer version from a JSON file in src directory with the content {**"jplag_version"**:{"major":0,"minor":0,"patch":0}}.

"jplag_version" should be "report-viewer_version", i think.

**Comment by sebinside** [comment]
@cyfml You are right but I would prefer `report_viewer_version` to keep it consistent.

**Comment by cyfml** [comment]
@sebinside  I am not clear, what does stopping working after several clicks means. I tested just now, i didn't find this problem. Let me introduce two clicks. 
1. When you click the match in the `matchTable`, it will just open the corresponding files. 
2. When you close one file and click the highlighting in the `CodePanel`, it will also just open the corresponding file.

**Comment by sebinside** [comment]
That's also what I tested. But after several matches (e.g., quickly clicking on all possible matches in a row), it stopped working after some clicks. I'm not able to properly replicate this for now.

**Comment by cyfml** [comment]
@sebinside Maybe there are serval matches in the same two-files-pair. when you click the first match, it opens two files. When you click second match, this match has the same files as the first match. So it has no reaction, because these two files are already opened.

**Comment by sebinside** [comment]
@cyfml Ah, that might be the solution, I did not think of that. However, in this case, the view should scroll to this match as well (just like the view scrolls to the first match if the file is opened). So maybe this could be easily fixed by you.

**Comment by cyfml** [comment]
@sebinside I spent some time to find reason. The reason is that, submissionId has already transformed into normal path(e.g. root1_A=>root1/A). DOM can't find the corresponding element by id. This id is codelPanelId+submissionId+lineNumber. So it can't scroll automatically.

**Comment by cyfml** [comment]
@tsaglam last merged PR fixed this problem: Enable collapsing by clicking on the file header in the comparison view. Could you mark it as finished and quote the PR number? Thanks.

**Comment by tsaglam** [comment]
@sebinside @cyfml sometimes I encounter this:
![grafik](https://user-images.githubusercontent.com/4396919/221190256-96cb194f-ec4a-4dd6-a7a6-c459c6d843b1.png)

This is a data set of 85 submissions, argument `-n 1000` and thus 3655 comparisons in total.

**Comment by cyfml** [comment]
@tsaglam Because there is only one parameter in zip file. This parameter is totalComparisons(3655). But if you use zip file generated before, there is no this field in zip. Are you sure, there is a field(totalComparisons) in zip file?

**Comment by cyfml** [comment]
Report-viewer don't know the totalComparisons. The solution might report-viewer don't show this info when using zip file generated by last version of Jplag.

**Comment by tsaglam** [comment]
> Because there is only one parameter in zip file. This parameter is totalComparisons(3655). But if you use zip file generated before, there is no this field in zip. Are you sure, there is a field(totalComparisons) in zip file?

Ah, it could be an older jar, I am not sure but I can check.

> Report-viewer don't know the totalComparisons. The solution might report-viewer don't show this info when using zip file generated by last version of Jplag.

I think this would be an elegant solution!
